bracketSpacing: true
endOfLine: "auto"
printWidth: 100
proseWrap: "always"
singleQuote: false
tabWidth: 3
trailingComma: "all"

overrides:
   - files: "*.sol"
     options:
        compiler: "0.8.17"
        tabWidth: 3
   - files: "*.js"
   - files: "*.ts"
