[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
program1 = "KBCe2H8VpgPh44QPURqj5uiywx93CG3j1rGtBY3TXLY"
program2 = "572U58pCWdwqk3NF2qjsmsHmeUmLtNokt3ZgJLbaNeib"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
